[package]
name = "runner"
version = "0.4.0"
authors = ["steve donovan <steve.j.donovan@gmail.com>"]
description = "Utility for running Rust snippets"

documentation = "https://docs.rs/crate/runner"
repository = "https://github.com/stevedonovan/runner"
edition = "2018"

readme = "readme.md"

keywords = ["compiler-runner","scripting","snippets"]

license = "MIT"

[dependencies]
easy-shortcuts = "0.3"
lapp = "0.4"
open = "1.2"
lazy_static = "0.2"
semver = "0.9"
json = "0.11"
isatty = "0.1.8"
toml = "0.4.5"
serde_derive = "1.0.27"
serde = "1.0.27"
shlex = "0.1.1"
dirs = "1.0"

[profile.release]
panic = 'abort'





